### PR TITLE
"meteor npm/node" should return exit code from command

### LINKED ISSUE #6673: [1.3] "meteor npm run some-script-name" doesn't pass through correct exit status
The new `meteor npm` command is fantastic, however, when you use `meteor npm run some-script-name`, the exit status from `some-script-name` isn't passed through the same as it would be with the traditional `npm run some-script-name`.  Even though the meteor command is proxying the command to npm, it should still return the correct exit status from the script.

#### package.json
```
{
  "name": "npm-run-exit-status",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "crash-hard": "echo \"This should fail\" && exit 1"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0"
  }
}
```

#### Normal "npm run" result
```bash
$ # Note the lack of "meteor" here
$ npm run crash-hard

> npm-run-exit-status@ crash-hard /Users/jesse/Dev/npm-run-exit-status
> echo "This should fail" && exit 1

This should fail

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/jesse/.nvm/versions/node/v5.6.0/bin/node" "/Users/jesse/.nvm/versions/node/v5.6.0/bin/npm" "run" "crash-hard"
npm ERR! node v5.6.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! npm-run-exit-status@ crash-hard: `echo "This should fail" && exit 1`
npm ERR! Exit status 1
npm ERR! 
...snip npm error stuff, contact npm owner, blah blah...
$ echo $?
1
$ # Correct exit code!
```

#### New "meteor npm run" result
```bash
$ # Note the inclusion of "meteor" here
$ meteor npm run crash-hard

> npm-run-exit-status@ crash-hard /Users/jesse/Dev/npm-run-exit-status
> echo "This should fail" && exit 1

This should fail

npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/Users/jesse/.meteor/packages/meteor-tool/.1.3.0_3.i8crvt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "run" "crash-hard"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22
npm ERR! code ELIFECYCLE
npm ERR! npm-run-exit-status@ crash-hard: `echo "This should fail" && exit 1`
npm ERR! Exit status 1
npm ERR! 
...snip npm error stuff, contact npm owner, blah blah...
$ echo $?
0
$ # Exit Code should have been 1
```

### PR DESCRIPTION
**Pull request by abernix**
Fixes #6673

The Meteor "dev bundle bin commands" which proxy through to the
meteor version of npm/node was not returning the exit code from the
command which it executed.  This creates problems for things like
`meteor npm run script-name` when the exit code is important.  This
comes into play when you run npm scripts which run tests, lint code, etc.

This fix causes the meteor-tool to process.exit with the spawned process
exit code.

Windows Disclaimer: I used the same flush-buffers-on-exit-in-windows
that the tool/cli/main.js uses because I would assume the same problem
exists, however, I don't have the Windows environment to test or confirm
that this code works at all.

Also, couldn't find any tests that directly tested this dev bundle
bin-command passing scenario (though hard to search through them all),
so I created a barebones test app and tests.

### CODE REVIEW

File: tools/index.js [hunk 1]
```diff
@@ -1,4 +1,18 @@
...
+  // Node 0.12, so when we upgrade let's remember to remove this clause, and the
+  // file it requires. See https://github.com/joyent/node/issues/3584
+  // This same comment and require is in ./cli/main.js
+  if (process.platform === 'win32') {
+    require('./tool-env/flush-buffers-on-exit-in-windows.js');
+  }
+
+  spawnBinProcess.on('exit', function (exitCode) {
+    process.exit(exitCode);
+  });
```
Comment (benjamn) [inline tools/index.js]: I would prefer to have this exit code logic inside the `./cli/dev-bundle-bin-commands.js` module.

**Comment by benjamn** [comment]
This is awesome!
