### PR TITLE
Fix for #14013

### LINKED ISSUE #14013: Calling Roles.getUsersInRoleAsync with certain queryOptions can lead to errors
Hi all,

using the `queryOptions` attribute in `Roles.getUsersInRoleAsync` can cause unintended behaviour and errors. For example, if you pass `{queryOptions: { fields: { _id : 1 }}}` to the call, you'll receive an error when calling the method.

The reason is, that the queryOptions also get passed to the internal `Roles.getUserAssignmentsForRole` call, namely via the `options` parameter, but those `options = { queryOptions }` get also passed to the `role-assignments` collection, resulting in the example in filtering out `user._id` information, which leads to errors.

https://github.com/meteor/meteor/blob/335994633ca1833f2d5d365b3f40fe30d7452a8b/packages/roles/roles_common_async.js#L1042-L1063

This occurs in the current version 1.0.1 of the `roles` package. I think I can pull of a PR on this issue, by simply removing the queryOptions from the options object passed to the `Roles.getUserAssignmentsForRole` call. This will match the docs, since the options are only supposed to be passed to the users collection.

Also, there is an undocumented third parameter `queryOptions` for `Roles.getUsersInRoleAsync`, which could be discussed to be removed, since `options.queryOptions` also specifies queryOptions for the users cursor.

### PR DESCRIPTION
**Pull request by bratelefant**
This is my attempt to fix [this issue related to the roles package](https://github.com/meteor/meteor/issues/14013).

I'd like to add a test, that reproduces the issue and proves, that this PR fixes that; is there a way to test a package in my meteor fork directly, without having to create a sample project?

### CODE REVIEW

**Comment by nachocodoner** [comment]
Thanks for the fix to this issue you reported!

> is there a way to test a package in my meteor fork directly, without having to create a sample project?

You can run the test suite with the test you provided with `<path-to-checkout>/meteor test-packages roles`. You can use `TINYTEST_FILTER="<name-of-test>"` to just run the test you like and re-run on changes. (also `--filter`/`-f `should work as well as the env var) 

Alternatively, you can run any app from your Meteor checkout. You just need to run the app using `<path-to-checkout>/meteor run`. This will use the Roles version from the checkout when testing the app that depends on the Roles package.

File: packages/roles/roles_common_async.js [hunk 1]
```diff
@@ -1052,8 +1052,13 @@ Object.assign(Roles, {
    * @return {Promise<Cursor>} Cursor of users in roles.
    */
   getUsersInRoleAsync: async function (roles, options, queryOptions) {
+    options = Roles._normalizeOptions(options)
+    
+    const assignmentOptions = { ...options }
+    delete assignmentOptions.queryOptions
```
Comment (Grubba27) [inline packages/roles/roles_common_async.js]:
```suggestion
   assignmentOptions.queryOptions = undefined 
```

I think we try not to use `delete` (cc @italojs)

Comment (italojs) [reply packages/roles/roles_common_async.js]: delete statement isnt a good practice for "hot code" and roles would be high requested in big projects that uses meteor.

`Delete` statement prevent V8 JIT to optmize this funciton since it change the original schema in runtime 

References: 
- https://leapcell.io/blog/unlocking-node-js-performance-through-smarter-v8-jit-interactions
- https://www.thenodebook.com/node-arch/v8-engine-intro#myth-1-v8-is-just-an-interpreter

[Benchmark](https://github.com/ishtms/v8-perf)

**Review by italojs — CHANGES_REQUESTED** [review]

File: packages/roles/roles_common_async.js (hunk 1 above)
Comment (bratelefant) [reply packages/roles/roles_common_async.js]: @italojs interesting read, thanks for pointing that out, wasn't aware of that; will review my own codebase now as well... ;)

**Review by italojs — APPROVED** [review]
