### PR TITLE
Fix(webapp): Remove Vary: User-Agent header from hashed assets (#13852)

### LINKED ISSUE #13852: Can Vary: User-Agent in webapp_server.js Be Removed?
https://github.com/meteor/meteor/blob/e7d0884324a3fb2801c99e96c2487aea2cee62b5/packages/webapp/webapp_server.js#L684-L690

I'm using a CDN to cache static files, but I noticed that the cache hit rate is lower than expected. Upon inspecting the requests, I found that the `Vary` header is set to `User-Agent`. Since there are a vast number of user agents, this significantly reduces CDN cache efficiency.

I checked the Meteor bundle contents and noticed that the JS filenames differ between `web.browser` and `web.browser.legacy`. Does this mean `Vary: User-Agent` is no longer necessary?

This code was introduced in 2018 (Commit 182c426).

### PR DESCRIPTION
**Pull request by shamshad-ansari**
# Fix: Remove Vary: User-Agent header from hashed static assets to improve CDN cache efficiency

Fixes #13852

## Summary

This PR optimizes CDN caching behavior for static assets served by the `webapp` package by conditionally removing the `Vary: User-Agent` header from production builds with content-hashed filenames.

## Problem

Currently, Meteor sends `Vary: User-Agent` for all static files. This header instructs CDNs (such as Cloudflare or CloudFront) to create separate cache entries for every unique User-Agent string. This results in:

- Significantly reduced cache hit rates
- Increased origin bandwidth usage
- Higher CDN storage costs
- Slower page loads for end users

With thousands of different User-Agent strings in production (Chrome, Firefox, Safari, mobile browsers, bots, etc.), CDNs end up storing hundreds or thousands of duplicate copies of identical files.

## Solution

This PR modifies `webapp_server.js` to conditionally apply the `Vary: User-Agent` header based on whether a resource has a content hash in its filename.

### Implementation Details

**Production (Hashed Filenames):**
- Files with the hash in the pathname (e.g., `/app.abc12345.js`) no longer receive the `Vary: User-Agent` header
- The pathname uniquely identifies the content per architecture (modern vs legacy)
- This allows efficient CDN caching with natural cache separation

**Development (Unhashed Filenames):**
- Files without the hash in the pathname (e.g., `/packages/promise.js?hash=abc123`) retain the `Vary: User-Agent` header
- Prevents cache poisoning in development workflows
- Maintains backward compatibility with existing development practices

**Configuration Option:**
The behavior can be controlled via `Meteor.settings`:
```javascript
{
  "packages": {
    "webapp": {
      "includeVaryUserAgent": false 
    }
  }
}
```

Default value is `true` to maintain backward compatibility.

### Code Changes

Modified `packages/webapp/webapp_server.js` (lines 688-693):
```javascript
// Before:
if (info.cacheable) {
  res.setHeader('Vary', 'User-Agent');
}

// After:
const varyAgentMode = Meteor.settings.packages?.webapp?.includeVaryUserAgent ?? true;

if (info.cacheable && !pathname.includes(info.hash) && varyAgentMode) {
  res.setHeader('Vary', 'User-Agent');
}
```

## Tests

Added comprehensive test coverage in `webapp_tests.js` to verify optimization, safety, and configuration:

**Test 1: Optimization Verification (Production Scenarios)**
- Confirms that files with a hash in their filename (e.g., `/app.abc12345.js`) **do not** receive the `Vary: User-Agent` header.
- Validates that production builds will benefit from improved CDN caching by treating these assets as immutable.

**Test 2: Safety Verification (Development Scenarios)**
- Confirms that files *without* a hash in the URL (e.g., `/packages/modules.js`) **retain** the `Vary: User-Agent` header, even if they have an internal ETag hash.

**Test 3: Configuration Verification**
- Verifies that the new behavior respects the `includeVaryUserAgent` setting.
- Confirms that users can explicitly disable the optimization (reverting to old behavior) or force headers if required by their specific infrastructure.

**Test 4: Consistency Verification**
- Validates that hashed URLs return identical content bytes regardless of the User-Agent (Modern vs. Legacy).
- Confirms that the "Modern/Legacy" bundle split is handled strictly by the URL hash, proving that removing the `Vary` header is safe for these specific files.

## Verification

- Version bumped from `2.1.0` to `2.1.1` (patch release)
- All existing tests pass
- New tests verify both optimization and safety
- Code formatting follows project conventions
- No breaking changes
- Backward compatible (default behavior maintained via configuration)

## Summary by CodeRabbit

* **New Features**
  * Optimized HTTP caching for static assets: hashed asset URLs now exclude the Vary: User-Agent header to improve browser cache efficiency, while unhashed URLs retain it to prevent cross-browser cache issues.
  * Added configuration setting to control Vary: User-Agent header behavior for static files (enabled by default).

* **Tests**
  * Added test coverage for HTTP caching header behavior.

* **Documentation**
  * Documented the new static assets caching optimization and configuration option.

### CODE REVIEW

**Comment by italojs** [comment]
would be good to have a doc about it (inside v3-docs/)

File: packages/webapp/webapp_server.js [hunk 1]
```diff
@@ -681,11 +681,14 @@ WebAppInternals.staticFilesMiddleware = async function(
...
-    // to invalidate cached resources when/if its user agent string
-    // changes in the future.
+  // Resources identified by a hash (info.hash) are unique per
+  // architecture (modern vs legacy), so Vary: User-Agent is redundant.
+  //
+  // However, in Development/Test mode, hashes might be identical or missing,
+  // so we force Vary to be safe.
+  const varyAgentMode = Meteor.settings.packages?.webapp?.varyAgent ?? true;
+
+  if (info.cacheable && !info.hash && varyAgentMode) {
```
Comment (nachocodoner) [inline packages/webapp/webapp_server.js]: `info.hash` exists all the time in development and production mode, at least based on my debugging on a real app. Did you debug this on a real app with these changes?

What needs to be compared is whether `path` already contains `info.hash` or not. If it does not contain the hash, then add `res.setHeader('Vary', 'User-Agent')`.

File: packages/webapp/webapp_tests.js [hunk 2]
```diff
@@ -432,3 +432,112 @@ Tinytest.addAsync("webapp - parse url queries", async function (test) {
...
+  async function (test) {
+    const arch = 'web.browser';
+    const unhashedJs = '/safety-unhashed.js';
+
+    // Inject mock development file (no hash).
+    WebAppInternals.staticFilesByArch[arch][unhashedJs] = {
+      content: 'console.log("dev")',
+      absolutePath: '/tmp/mock-dev.js',
+      cacheable: true,
+      hash: null,
```
Comment (nachocodoner) [inline packages/webapp/webapp_tests.js]: This mock doesn't look accurate. hash gets calculated all the time on a real Meteor app running.

Please debug this on a real Meteor app to confirm what info it contains in `meteor run` vs `meteor run --production`, you will see how `hash` is always present, but what changes is if the file requested contains the hash or not in the path/file name.

File: packages/webapp/webapp_server.js (hunk 1 above)
Comment (shamshad-ansari) [reply packages/webapp/webapp_server.js]: @nachocodoner Yes, I debugged this on a real app with the changes and found that the header was removed in both production and development. I was initially confused because I thought you meant that `info.hash` was not present in development, which is why I wrote the tests the way I did.

After adding some `console.log` statements, I understood your point. I can confirm that the hash is always present in both production and development, but in development the filename does not include the hash, while in production it does. Here are the screenshots:

Development mode - hash present in info but not in pathname

Production mode - hash present in both info and pathname

I'll go ahead and update the code like this:
```javascript
if (info.cacheable && !pathname.includes(info.hash) && varyAgentMode) {
  res.setHeader("Vary", "User-Agent");
}
```

I also verified this manually in the Network tab and it works as expected. Next, I'll update the tests to properly reflect this behavior.

**Review by nachocodoner — APPROVED** [review]
