### PR TITLE
[Rspack][SWC] fix: add support for swc.config.ts in meteor 3.4

### LINKED ISSUE #14033: [Meteor 3.4] Cant use swc.config.ts
In a Meteor 3.4 app using the TypeScript template, I cannot use swc.config.ts. I can see swc.config.js and .swcrc work but in .ts, it does not work.

### PR DESCRIPTION
**Pull request by sanki92**
## Problem

Meteor's Rspack integration currently only supports `.swcrc` and `swc.config.js` for SWC transpiler configuration. TS developers can't use `swc.config.ts` for type-safe configs, which is a common pattern in modern TS projects.

## Solution

Extended the SWC config loader to support `.ts` files:

• Added TS file handling with automatic transpilation (esbuild primary, regex fallback)
• Maintains priority order: `.swcrc` > `swc.config.js` > `swc.config.ts`
• Added `swc.config.ts` to Rspack cache dependencies for proper invalidation

### `npm-packages/meteor-rspack/lib/swc.js`
• Extended `getMeteorAppSwcrc()` to handle `.ts` extensions
• Added TS transpilation with esbuild (falls back to regex if unavailable)
• Strips TS syntax: imports, types, interfaces, decorators
• Converts ES modules to CommonJS
• Updated `getMeteorAppSwcConfig()` to check for all three config types

### `npm-packages/meteor-rspack/rspack.config.js`
• Added `swc.config.ts` path detection
• Included in build dependencies for cache invalidation

## Verification

Tested with Meteor TS app:

• Only `swc.config.ts` present - loads correctly
• Both `swc.config.js` and `swc.config.ts` present - `swc.config.js` takes priority
• All three configs present - `.swcrc` takes priority

Example `swc.config.ts`:
```typescript
import type { Config } from '@swc/core';

const config: Config = {
  jsc: {
    target: 'es2020',
    parser: {
      syntax: 'typescript',
      tsx: true,
      decorators: true,
    },
  },
  sourceMaps: true,
};

export default config;
```

Fixes #14033

### CODE REVIEW

**Review by nachocodoner — CHANGES_REQUESTED** [review]
In `packages/babel-compiler/babel-compiler.js`, there is also code around `.swcrc`/`swc.config.js` file usage. This is used by the Meteor bundler with modern:true in Meteor 3.3, not only by the Rspack integration that came later. It should also support swc.config.ts in the Meteor bundler, along with Meteor Rspack that you already cover.

Again, thanks to this proactivity on helping us to fix these issues.

File: npm-packages/meteor-rspack/lib/swc.js [hunk 1]
```diff
@@ -9,12 +9,32 @@ const vm = require('vm');
...
+    if (file.endsWith('.js') || file.endsWith('.ts')) {
       let content = fs.readFileSync(filePath, 'utf-8');
-      // Check if the content uses ES module syntax (export default)
-      if (content.includes('export default')) {
-        // Transform ES module syntax to CommonJS
-        content = content.replace(/export\s+default\s+/, 'module.exports = ');
+      
+      if (file.endsWith('.ts')) {
+        try {
+          const esbuild = require('esbuild');
```
Comment (nachocodoner) [inline npm-packages/meteor-rspack/lib/swc.js]: why do you use esbuild here?

We already benefit from @swc/core (builtin in Rspack), why don't use swc here to transform this file?

Comment (sanki92) [reply npm-packages/meteor-rspack/lib/swc.js]: Ahh you're right, my bad, didn't think to check what Rspack already had bundled. I was focused on getting the TS parsing working and just reached for esbuild. Makes way more sense to use what's already there.

And yeah, completely missed that babel-compiler needed this too. I was only testing through the Rspack path. Fixed now, but let me know if you see anything else.

File: npm-packages/meteor-node-stubs/package.json [hunk 2]
```diff
@@ -2,7 +2,7 @@
   "name": "meteor-node-stubs",
   "author": "Ben Newman <ben@meteor.com>",
   "description": "Stub implementations of Node built-in modules, a la Browserify",
-  "version": "1.2.24",
+  "version": "1.2.26",
```
Comment (nachocodoner) [inline npm-packages/meteor-node-stubs/package.json:5]: Why `meteor-node-stubs` was bumped here?

Comment (sanki92) [reply npm-packages/meteor-node-stubs/package.json:5]: My branch accidentally included those commits because I branched from devel, and when you changed the PR base to release-3.4.1, it picked up the extra commits.

Just cleaned it up, Should be good now, Sorry for the inconvenience :)

**Comment by sanki92** [comment]
Hey @nachocodoner, caught one more issue while re-reviewing, the SWC transform had `module: { type: 'commonjs' }`, which converts `export default config` into `exports.default = config`. That means the vm sandbox wraps the config in `{ default: config }`, so the user's SWC options would silently get lost during merge.

Fixed by removing the `module` option, SWC now only strips TypeScript syntax and keeps `export default` as-is, which the existing handler already converts to `module.exports =`. Also added a `__esModule` safety guard in case SWC's default module behavior ever changes. Applied to both swc.js and babel-compiler.js.

Please take a look and lmk if you see anything else that needs adjustment.

**Review by nachocodoner — APPROVED** [review]
Approved and merging it, @sanki92. I applied the last round of tweaks on your changes on this PR, https://github.com/meteor/meteor/pull/14233. Feel free to check them out, but there are just to provide more docs, E2E test and fix an issue I found on my way to validate your work.

Thanks again for this contribution. Your proactivity with Meteor contributions is great to see. Good work!
