### PR TITLE
[FIX] The filtered positional operator $[<identifier>] (arrayFilters) does not work in Mongo update

### LINKED ISSUE #10103: The filtered positional operator $[<identifier>] (arrayFilters) does not work in Mongo update.
❗️ Bug or missing docs about array filter option in Mongo update.

Meteor version: `Meteor 1.7.0.3`

## Short description

In mongo 3.6 there is avaliable filtered positional operator `$[<identifier>]`. Described here:

> https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/

Using this was not possible before `Meteor v1.7` because of `mongodb` driver had version `2`. From `Meteor v1.7` we updated `mongodb` to `3` so implementation of `positional filter operator` should be possible now.

This problem was mentioned in issue:

> https://github.com/meteor/meteor-feature-requests/issues/268

Although of update `mongodb` from `2.2.34` to `3.0.5` in https://github.com/meteor/meteor/pull/9790/files `filtered positional operator` still not works.

## How it should work (mongo shell)

Login to mongo shell and create simplest possible resource that allow to reproduce problem eg.:

    db.insert({_id: 'crons'}, {_id: 'crons', value: [{name: 'getList', interval: 1000},{name: 'getOffer', interval: 1000}]});

Next use `filtered positional operator $[<identifier>]` to observe how it should work:

    db.configs.update({_id:'crons'},{ $set: { "value.$[elem].interval": 0 } },{ arrayFilters: [ {"elem.name": "getOffer"} ] })

Now you should see that resource looks like this:

    {
	    "_id" : "crons",
	    "value" : [ { "name" : "getList", "interval" : 1000 },
		        { "name" : "getOffer", "interval" : 0 } ]
    }

You can see that interval was changed for value with name "getOffer".

## How it **does not** work with meteor

Create simple method that repeats updated with arrayFilters key in third argument of update:

```
Meteor.methods({
        'config.update-cron-interval'({name, interval}) {
            check(name, String);
            check(interval, Number);

            Configs.update(
                {_id: 'crons'},
                { $set: { "value.$[elem].interval": interval } },
                {arrayFilters: [{"elem.name": name}]}
            );
        }
    })
```

Calling this method throws error:

```
I20180727-16:51:49.895(2)? { MongoError: No array filter found for identifier 'elem' in path 'value.$[elem].interval'
I20180727-16:51:49.895(2)?     at Function.MongoError.create (/home/daniel/.meteor/packages/npm-mongo/.3.0.7.bpkgyk.3f1fv++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/error.js:45:10)
I20180727-16:51:49.896(2)?     at toError (/home/daniel/.meteor/packages/npm-mongo/.3.0.7.bpkgyk.3f1fv++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:149:22)
I20180727-16:51:49.896(2)?     at /home/daniel/.meteor/packages/npm-mongo/.3.0.7.bpkgyk.3f1fv++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:1029:39
I20180727-16:51:49.896(2)?     at /home/daniel/.meteor/packages/npm-mongo/.3.0.7.bpkgyk.3f1fv++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:544:18
I20180727-16:51:49.896(2)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20180727-16:51:49.897(2)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
I20180727-16:51:49.897(2)?   name: 'MongoError',
I20180727-16:51:49.897(2)?   message: 'No array filter found for identifier \'elem\' in path \'value.$[elem].interval\'',
I20180727-16:51:49.897(2)?   driver: true,
I20180727-16:51:49.897(2)?   index: 0,
I20180727-16:51:49.898(2)?   code: 2,
I20180727-16:51:49.898(2)?   errmsg: 'No array filter found for identifier \'elem\' in path \'value.$[elem].interval\'' }
```

## Temporary workaround

Instead mentioned update we can do the following things

1) query `findOne`
2) transform object in javascript
3) query `update`

In this case we can do:

    const crons = Configs.findOne({_id: 'crons'});

    crons.value = crons.value.map(e => { if(e.name===name) { e.interval = interval } return e; });

    Configs.update({_id: 'crons'}, crons );

But it would be better if this feature will be implemented or lacking implementation could be mentioned in docs.

### PR DESCRIPTION
**Pull request by AlexSterk**
Adds support for the arrayFilters option for Collection.update (see https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/), as described in #10103 .

This option only works server-side, for client-side there is a PR: #9721

Fixes #10103

I'm not entirely sure how to write an automated test for it, but I have verified the fix by creating a toy project, and running the example given by @gustawdaniel in the original issue.

Note: This is my first contribution to Meteor or an open-source project in general. I'm still learning so I would love some feedback. If you need me to also update the tests or documentation, don't hesitate to let me know!

### CODE REVIEW

File: packages/mongo/mongo_driver.js [hunk 1]
```diff
@@ -506,6 +506,8 @@ MongoConnection.prototype._update = function (collection_name, selector, mod,
   try {
     var collection = self.rawCollection(collection_name);
     var mongoOpts = {safe: true};
+    // Add support for filtered positional operator
+    if (_.has(options, 'arrayFilters')) mongoOpts.arrayFilters = options.arrayFilters;
```
Comment (StorytellerCZ) [inline packages/mongo/mongo_driver.js]: Is Underscore really needed here? Wouldn't
```js
options.hasOwnProperty('arrayFilters')
```
be enough?

Comment (AlexSterk) [reply packages/mongo/mongo_driver.js]: You're right. I saw Underscore being used this way in a number of files, so I assumed it was some code convention. I've replaced it with your suggestion

Comment (AlexSterk) [reply packages/mongo/mongo_driver.js]: As it turns out, using `hasOwnProperty` instead of Underscore causes test failures? I'm not sure how to proceed in this situation, should I just change it back?

Comment (simonbelanger) [reply packages/mongo/mongo_driver.js]: might be because `options` might be `null` and underscore is able to handle that?

Comment (AlexSterk) [reply packages/mongo/mongo_driver.js]: That could be it, but the next couple of lines, using `options.upsert` and `options.multi`

Comment (simonbelanger) [reply packages/mongo/mongo_driver.js]: 🤔 you're right... awesome PR btw, can't wait to use `arrayFilters` without  relying on `rawCollection()`, it's a bit a bit awkward to bypass Meteor collection when using `redis-oplog`

**Comment by mostlyfabulous** [comment]
I'm really looking forward to this PR being merged in.
@filipenevola, are there any plans to add this in to an upcoming beta or release?

**Comment by filipenevola** [comment]
Published mongo@1.9.1.

**Comment by ni-ko-o-kin** [comment]
@filipenevola I think  the documentation is missing. Are there plans to remove this feature again or is this planned to keep?

**Comment by filipenevola** [comment]
hi @ni-ko-o-kin , no plans to remove it.

@AlexSterk could you include this in the docs?

**Comment by AlexSterk** [comment]
> hi @ni-ko-o-kin , no plans to remove it.
> 
> @AlexSterk could you include this in the docs?

No problem. The PR can be found here: https://github.com/meteor/meteor/pull/11237
