### PR TITLE
Mitigate MongoDB cursor leak: synchronize next() and close() operations

### LINKED ISSUE #13783: OPLog tailing in Meteor 3.1 and 3.2 results in infinite number of cursors in Mongo database server
- Version with problem: every version from Meteor 3.1.1 onwards (introduction of Mongo 6 Node driver)
- Latest version without problem: Meteor 3.0.4
- OS: Galaxy provided OS, for local reproduction: MacOS 13.4 Ventura; database server: Mongo 6.0.5, Mongo 6.0.22
- Expected behavior: 
Every time OPLog tailing cursor is timed out after 30 seconds, it should not only be "killed" in the Mongo driver codebase, but the driver should also send the command to cleanup that cursor on the Mongo server side

This can be verified by the following check:
`db.serverStatus().metrics.cursor.open` command executed on Mongo server should not result in growing `total` number of opened cursors every 30 seconds

- Actual behavior: 
Whenever OPLog tailing cursor times out after 30 seconds (see: https://github.com/meteor/meteor/blob/release/METEOR%403.1.1/packages/mongo/asynchronous_cursor.js#L87) it attempts to `close` given cursor synchronously (see: https://github.com/meteor/meteor/blob/release/METEOR%403.1.1/packages/mongo/asynchronous_cursor.js#L90 and https://github.com/meteor/meteor/blob/release/METEOR%403.1.1/packages/mongo/asynchronous_cursor.js#L127) which already is problematic, because the Mongo 6.9 driver's `close` cursor method is asynchronous (see: https://github.com/mongodb/node-mongodb-native/blob/v6.9.0/src/cursor/abstract_cursor.ts#L479)

However, this alone is not enough for the problem to be consistently not removing cursor, this is only a race condition that could happen every now and then. The real problem is that the `nextObjectPromise` that races against the timeout (again, see: https://github.com/meteor/meteor/blob/release/METEOR%403.1.1/packages/mongo/asynchronous_cursor.js#L87) calls underneath cursor's `next` method (see: https://github.com/meteor/meteor/blob/release/METEOR%403.1.1/packages/mongo/asynchronous_cursor.js#L40) which happens to still execute when the `close` cursor method starts executing.

The result is that the cursor reaches the following check: https://github.com/mongodb/node-mongodb-native/blob/v6.9.0/src/cursor/abstract_cursor.ts#L781 which happens to be true, because at the very start of the cursor `close` this happens: https://github.com/mongodb/node-mongodb-native/blob/v6.9.0/src/cursor/abstract_cursor.ts#L795 followed by https://github.com/mongodb/node-mongodb-native/blob/v6.9.0/src/cursor/abstract_cursor.ts#L806

This means that the `cleanup` method is executed for the second time due to `next` method behavior and this time the whole try/catch section of that method is skipped (because `isKilled` is `true`) so it fasttracks to the `finally` section which ends the session (see: https://github.com/mongodb/node-mongodb-native/blob/v6.9.0/src/cursor/abstract_cursor.ts#L820). And then it goes back to the `cleanup` triggered by Meteor's attempt to close the cursor, and before the driver sends the command to "kill" the cursor on server side, it runs into the `MongoExpiredSessionError: Cannot use a session that has ended` exception (see: https://github.com/mongodb/node-mongodb-native/blob/v6.9.0/src/sessions.ts#L995, https://github.com/mongodb/node-mongodb-native/blob/v6.9.0/src/operations/kill_cursors.ts#L32 and https://github.com/mongodb/node-mongodb-native/blob/v6.9.0/src/cursor/abstract_cursor.ts#L809)

This can be verified by the following check:
`db.serverStatus().metrics.cursor.open` command executed on Mongo server shows that every 30 seconds there's a new open, non-pinned cursor created

- reproduction:
Because this happens when you create a default app via `meteor create` command I am not providing the repository with a reproduction. If this is not sufficient and you still need me to push the content of `meteor create` output to a public repository, please let me know, I will do it.

Steps:
1. Create meteor app using `meteor create meteor-oplog-issue --typescript`
2. Set `MONGO_URL` and `MONGO_OPLOG_URL` to your Mongo instance
3. Start app via `npm run start`
4. After a minute or so, start executing `db.serverStatus().metrics.cursor.open` command on your Mongo server every 30 seconds and check the `total` value in the returned object growing while the `pinned`

### PR DESCRIPTION
**Pull request by italojs**
Note: branch base is devel because release 3.x must to be updated with devel

## Description:
This PR addresses the MongoDB cursor leak issue  as reported in  issue #13783 

## Key changes:

- Adds concurrency control to `AsynchronousCursor` to prevent simultaneous `next()` and `close()` calls, avoiding race conditions.
- Ensures that when closing a cursor, any pending `next` operation is awaited before the cursor is actually closed.
- Adjusts the cursor lifecycle in the tail method to guarantee the previous cursor is fully closed before creating a new one.

These changes help ensure that the killCursor command is sent to the MongoDB server before the session ends, preventing the accumulation of open cursors and improving the reliability of OPLog tailing.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Given the severity I think this should be released standalone package patch.

**Comment by nachocodoner** [comment]
I’d like to run a [meteor/performance](https://github.com/meteor/performance) runtime check to see if the MongoDB driver upgrade starting in version 3.1.1 caused the regression.

File: packages/mongo/mongo_connection.js [hunk 1]
```diff
@@ -804,6 +804,8 @@ Object.assign(MongoConnection.prototype, {
     cursorDescription, ordered, callbacks, nonMutatingCallbacks) {
     var self = this;
     const collectionName = cursorDescription.collectionName;
+    
+    console.error('🔥 _observeChanges: CALLED with selector:', JSON.stringify(cursorDescription.selector));
```
Comment (nachocodoner) [inline packages/mongo/mongo_connection.js]: Can this be cleaned?

File: packages/mongo/asynchronous_cursor.js [hunk 2]
```diff
@@ -73,7 +83,7 @@ export class AsynchronousCursor {
   // Returns a promise which is resolved with the next object (like with
   // _nextObjectPromise) or rejected if the cursor doesn't return within
   // timeoutMS ms.
-  _nextObjectPromiseWithTimeout(timeoutMS) {
+  async _nextObjectPromiseWithTimeout(timeoutMS) {
```
Comment (Grubba27) [inline packages/mongo/asynchronous_cursor.js]: Why `async` if we are not awaiting anything in here?

File: packages/mongo/asynchronous_cursor.js [hunk 3]
```diff
@@ -84,12 +94,11 @@ export class AsynchronousCursor {
...
-    return Promise.race([nextObjectPromise, timeoutPromise])
-      .catch((err) => {
+      return Promise.race([nextObjectPromise, timeoutPromise]).catch(async err => {
         if (err === timeoutErr) {
-          this.close();
-          return;
+          return this.close();
         }
+        // If the error is not a timeout, rethrow it.
         throw err;
```
Comment (Grubba27) [inline packages/mongo/asynchronous_cursor.js]: same goes for this `async err`

File: packages/mongo/asynchronous_cursor.js [hunk 4]
```diff
@@ -36,9 +38,17 @@ export class AsynchronousCursor {
...
     try {
-      return this._dbCursor.next();
+      this._pendingNext = this._dbCursor.next();
+      const result = await this._pendingNext;
+      this._pendingNext = null;
+      return result;
     } catch (e) {
+      this._pendingNext = null;
       console.error(e);
     }
```
Comment (radekmie) [inline packages/mongo/asynchronous_cursor.js]: 1. It'd be more natural to reset the `_pendingNext` in a `finally` block.
2. Why is this `console.error` here? A failing cursor should prevent further iteration, not be silenced.

File: packages/mongo/asynchronous_cursor.js (hunk 2 above)
Comment (radekmie) [reply packages/mongo/asynchronous_cursor.js:86]: Actually, this entire function could look like this _(I also fixed the weird formatting)_:
```ts
  async _nextObjectPromiseWithTimeout(timeoutMS) {
    const nextObjectPromise = this._nextObjectPromise();
    if (!timeoutMS) {
      return nextObjectPromise;
    }

    const timeoutPromise = new Promise(resolve => {
      // On timeout, close the cursor.
      const timeoutId = setTimeout(() => {
        resolve(this.close());
      }, timeoutMS);

      // If the `_nextObjectPromise` returned first, cancel the timeout.
      nextObjectPromise.finally(() => {
        clearTimeout(timeoutId);
      });
    });

    return Promise.race([nextObjectPromise, timeoutPromise]);
  }
```

That's because currently, the `timeoutErr` is ignored ("swallowed" in the `catch`).

File: packages/mongo/asynchronous_cursor.js [hunk 5]
```diff
@@ -123,8 +132,19 @@ export class AsynchronousCursor {
...
+    if (this._pendingNext) {
+      try {
+        await this._pendingNext;
+      } catch (e) {
+        // ignore
+      }
+    }
+    if (this._dbCursor && typeof this._dbCursor.close === 'function') {
+      await this._dbCursor.close();
+    }
```
Comment (radekmie) [inline packages/mongo/asynchronous_cursor.js]: It wasn't here before - is it needed now? (I'm asking about both the check and the `await`.)

File: packages/mongo/mongo_connection.js [hunk 6]
```diff
@@ -882,10 +882,11 @@ Object.assign(MongoConnection.prototype, {
...
           try {
             matcher = new Minimongo.Matcher(cursorDescription.selector);
-            return true;
+            return !!matcher;
           } catch (e) {
-            // XXX make all compilation errors MinimongoError or something
-            //     so that this doesn't ignore unrelated exceptions
+            if (e.message && (e.message.includes('needs an array') )) {
+              throw e;
+            }
```
Comment (radekmie) [inline packages/mongo/mongo_connection.js]: This seems like an unrelated change that I think should be followed up in a separate PR. Also, there's no need to `!!matcher`, as its `constructor` never returns anything, so `new`ing it will always return an instance (i.e., an object).

File: packages/mongo/mongo_connection.js [hunk 7]
```diff
@@ -792,9 +792,9 @@ MongoConnection.prototype.tail = function (cursorDescription, docCallback, timeo
   });
 
   return {
-    stop: function () {
+    stop: async function () {
       stopped = true;
-      cursor.close();
+      await cursor.close();
```
Comment (radekmie) [inline packages/mongo/mongo_connection.js]: This sounds like a potentially breaking change. Also, it becomes `void | Promise<void>`, since the `ObserveHandle.prototype.stop` does not return a `Promise`.

File: packages/mongo/asynchronous_cursor.js (hunk 5 above)
Comment (italojs) [reply packages/mongo/asynchronous_cursor.js]: The cursor.next() method is used to get the next document from a cursor. Here, I wait for the cursor to finish its current operation before closing it.

Regarding the await: the function [close](https://github.com/mongodb/node-mongodb-native/blob/56b2e6d56d55520f7bc18918dcf707bd12075d7e/src/cursor/abstract_cursor.ts#L684) returns a Promise<void>. I use await to ensure the operation completes.

File: packages/mongo/asynchronous_cursor.js (hunk 4 above)
Comment (italojs) [reply packages/mongo/asynchronous_cursor.js]: 1. done
2. i just didn't touch on this implementation since the goal here was to fix the issue, i wasn't looking for improvements, but i'll take a look at it

File: packages/mongo/asynchronous_cursor.js (hunk 5 above)
Comment (italojs) [reply packages/mongo/asynchronous_cursor.js]: I did a few tests, it doesnt affect the final result(close the cursors), so i removed the await

File: packages/mongo/mongo_connection.js (hunk 7 above)
Comment (italojs) [reply packages/mongo/mongo_connection.js]: I did a few tests, it doesnt affect the final result(close the cursors), so i removed the async await

File: packages/mongo/asynchronous_cursor.js (hunk 3 above)
Comment (italojs) [reply packages/mongo/asynchronous_cursor.js]: addressed

File: packages/mongo/asynchronous_cursor.js (hunk 2 above)
Comment (italojs) [reply packages/mongo/asynchronous_cursor.js]: addressed

File: packages/mongo/mongo_connection.js (hunk 6 above)
Comment (italojs) [reply packages/mongo/mongo_connection.js]: Yeah, it looks like an unrelated change, but after the changes, the test  `observeChanges - bad query` was crashing because the `$in needs an array` error wasn't thrown
I refactored this part by adding a `QueryError` class, so we can throw all bad query syntax errors.

File: packages/mongo/asynchronous_cursor.js (hunk 4 above)
Comment (italojs) [reply packages/mongo/asynchronous_cursor.js]: 2 - The behavior to prevent further iteration is already handled when we return null from _rawNextObjectPromise. When this happens, _nextObjectPromise also returns null, which causes the iterator (next()) to return { done: true, value: null }. This properly signals the end of iteration to the consumer of the cursor, so no further documents will be processed. Therefore, even if the error is not thrown, returning null ensures that iteration is stopped as expected.

**Comment by italojs** [comment]
@radekmie changes addressed

File: packages/minimongo/common.js [hunk 8]
```diff
@@ -379,7 +386,7 @@ const VALUE_OPERATORS = {
     const branchedMatchers = operand.map(criterion => {
       // XXX handle $all/$elemMatch combination
       if (isOperatorObject(criterion)) {
-        throw Error('no $ expressions in $all');
+        throw new Error('no $ expressions in $all');
```
Comment (Grubba27) [inline packages/minimongo/common.js]: why not QueryError here?

File: packages/minimongo/common.js [hunk 9]
```diff
@@ -2,6 +2,13 @@ import LocalCollection from './local_collection.js';
 
 export const hasOwn = Object.prototype.hasOwnProperty;
 
+export class QueryError extends Error {
+  constructor(message) {
+    super(message);
+    this.name = 'QueryError';
```
Comment (Grubba27) [inline packages/minimongo/common.js]: You could move it to the class definition instead of the construction:

```js
class QueryError extends Error {
  name = 'QueryError';
}
```

File: packages/mongo/mongo_connection.js [hunk 10]
```diff
@@ -886,6 +886,9 @@ Object.assign(MongoConnection.prototype, {
           } catch (e) {
             // XXX make all compilation errors MinimongoError or something
             //     so that this doesn't ignore unrelated exceptions
+            if (e.name === 'QueryError') {
```
Comment (Grubba27) [inline packages/mongo/mongo_connection.js]: here you could call it via class definition too:

```js
 if (e.name === QueryError.name) {
```
or you could do:

```js
e.constructor.name === QueryError.name
```

File: packages/minimongo/common.js (hunk 8 above)
Comment (italojs) [reply packages/minimongo/common.js]: good catch, just missed it

File: packages/mongo/mongo_connection.js (hunk 10 above)
Comment (radekmie) [reply packages/mongo/mongo_connection.js]: And how about `instanceof`?

**Review by nachocodoner — APPROVED** [review]

File: packages/minimongo/common.js [hunk 11]
```diff
@@ -2,6 +2,12 @@ import LocalCollection from './local_collection.js';
 
 export const hasOwn = Object.prototype.hasOwnProperty;
 
+export class MiniMongoQueryError extends Error {
+  constructor(message) {
+    super(message);
+  }
+}
+
```
Comment (Grubba27) [inline packages/minimongo/common.js]:
```suggestion
export class MiniMongoQueryError extends Error {}
```
