### PR TITLE
Fix `Match.Optional` to work as it did previously in Meteor 1.2

### LINKED ISSUE #6735: [1.3] `check`'s Match.Optional now allows "null" (contrary to plan)
As found during research for the problem in  #6712, `Match.Optional` now matches `null` when it had not before 1.3.  The (ultimate) decision in Issue #3876 was to keep `Match.Optional` the same (allow `undefined`) and introduce a new `Match.Maybe` which would match `null` and `undefined` in order to **NOT** do this:

> silently change the (`Match.Optional`) behavior because it could introduce undiscoverable security holes into people's apps

Unfortunately, the way that that #6220 was done, it literally did exactly that, and there was no Match test in place to make sure that `null` did not pass `Match.Optional`.

I have an incoming PR to fix this.  This Issue is just for the record.

### PR DESCRIPTION
**Pull request by abernix**
`Match.Optional` is still only supposed to "pass" if the value is `null`
or the specified type.  The new `Match.Maybe` allows `undefined` or
`null` in addition to the specified types. `Match.Optional` is on the
track toward deprecation, however to not break existing code it was
*supposed* to stay working the same as before. (per #3876).

There weren't tests in place to make sure that `Match.Optional` kept
working the same, and the code didn't actually make it keep working the
same.  Hopefully extra tests will make this better.

`.Maybe` has some additional bugs, but should be addressed separately
(see #6712)

Fixes #6735

### CODE REVIEW

File: packages/check/match.js [hunk 1]
```diff
@@ -115,7 +115,9 @@ var Optional = function (pattern) {
   this.pattern = pattern;
 };
 
-var Maybe = Optional;
+var Maybe = function (pattern) {
+  this.pattern = pattern;
+};
```
Comment (abernix) [inline packages/check/match.js]: Line 256 below is where the real problem happened since it's an `elseif` that never got reached anymore since both `.Maybe` and `.Optional` were the same object.

**Comment by abernix** [comment]
^^ Updated PR/commit reference to dyslexic "other" issue number I had in my commit msg.  Should be #6712.  Silly, Abernix.
