### PR TITLE
Fix ROOT_URL path prefix stripping.

### LINKED ISSUE #10019: [1.7.0.3] Error when using custom ROOT_URL
Meteor version with the problem: `1.7.0.3`
Last tested Meteor version without the problem: `1.6.0.1`
OS: macOS High Sierra
Expected behavior: Should be able to visit page `localhost:3000/app` normally.
Actual behavior: App does not serve the page at all. See error below:

```
W20180622-04:14:07.379(-5)? (STDERR) (node:3757) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
W20180622-04:14:07.380(-5)? (STDERR)     at getArchAndPath (packages/webapp/webapp_server.js:520:15)
W20180622-04:14:07.380(-5)? (STDERR)     at getStaticFileInfo (packages/webapp/webapp_server.js:481:26)
W20180622-04:14:07.380(-5)? (STDERR)     at Object.WebAppInternals.staticFilesMiddleware (packages/webapp/webapp_server.js:406:16)
W20180622-04:14:07.380(-5)? (STDERR)     at packages/webapp/webapp_server.js:781:21
W20180622-04:14:07.381(-5)? (STDERR)     at /Users/xch/.meteor/packages/promise/.0.11.1.e1cv1x.nf15w++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180622-04:14:07.381(-5)? (STDERR) (node:3757) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Simple** reproduction: 

```
meteor create --full foobar
cd foobar
meteor npm i
ROOT_URL=http://localhost:3000/app meteor
```
image

Looks like the connection couldn't even be established.

### PR DESCRIPTION
**Pull request by benjamn**
Thanks to @Zodiase for doing most of the investigation here:
https://github.com/meteor/meteor/issues/10019#issuecomment-401225148

Fixes #10019.

### CODE REVIEW

File: packages/webapp/webapp_server.js [hunk 1]
```diff
@@ -748,27 +748,45 @@ function runWebAppServer() {
...
-    } else if (pathPrefix) {
+    const pathPrefix = __meteor_runtime_config__.ROOT_URL_PATH_PREFIX;
+    const { pathname } = parseUrl(request.url);
+
+    // check if the path in the url starts with the path prefix
+    if (pathPrefix) {
+      const prefixParts = getPathParts(pathPrefix);
+      const pathParts = getPathParts(pathname);
+      if (isPrefixOf(prefixParts, pathParts)) {
+        request.url = "/" + pathParts.slice(prefixParts.length).join("/");
```
Comment (benjamn) [inline packages/webapp/webapp_server.js]: Enforcing the leading `/` is the primary trick that fixes #10019, as @Zodiase discovered.
