### PR TITLE
Adjust Mongo.Collection._rewriteSelector to allow a custom fallback _id.

### LINKED ISSUE #6599: Inconsistent idGeneration behavior with insert and upsert
Hi there,

I encountered an issue while working with collections using MongoIds and upserting documents. It seems that when I upsert a new document, a string Id is always generated even if the idGeneration option is set to Mongo for this collection.

Here is a code snippet to reproduce the problem in Meteor 1.2.1:

```
var foo = new Mongo.Collection("foo", { idGeneration: "MONGO" });
foo.insert({ type: "insert" });
foo.update({ _id: null }, { bar: "update upsert" }, { upsert: true });
foo.upsert({ _id: null }, { bar: "upsert" });
```

Here are the docs viewed in Mongo shell:

```
{ "_id" : ObjectId("df0a4d11321b44bcf2be5621"), "type" : "insert" }
{ "_id" : "e6fiyMHCz87FLyRDQ", "bar" : "update upsert" }
{ "_id" : "FEptNXvQQ2SmNg4X5", "bar" : "upsert" }
```

I'm quite new to Meteor and I can't figure out precisely what's going wrong here, but it seems the wrong _makeNewID function is called when we're upserting.

### PR DESCRIPTION
**Pull request by hwillson**
Hi all - this PR is intended to help resolve #6599. Currently when a `{ _id: falsey }` selector is passed into the `Mongo.Collection._rewriteSelector` function, a new selector is returned with an auto-generated string `_id`. This causes a problem if a Collection has been configured to use a `options.idGeneration` value of `MONGO`, meaning `Mongo.ObjectID`'s should be used for `_id`'s. These changes allow a fallback ID of any type (string or ObjectID) to be passed into `Mongo.Collection._rewriteSelector`, that will be used instead of the auto-generated string `_id`, if present. I've then updated the main source of this problem, `Mongo.Collection.prototype.update` (when upserting), to make sure a proper fallback ID of either string or `ObjectID` type is passed into `Mongo.Collection._rewriteSelector`. Thanks!

### CODE REVIEW

File: packages/mongo/collection.js [hunk 1]
```diff
@@ -361,8 +361,10 @@ Mongo.Collection._publishCursor = function (cursor, sub, collection) {
 // protect against dangerous selectors.  falsey and {_id: falsey} are both
 // likely programmer error, and not what you want, particularly for destructive
 // operations.  JS regexps don't serialize over DDP but can be trivially
-// replaced by $regex.
-Mongo.Collection._rewriteSelector = function (selector) {
+// replaced by $regex. If a falsey _id is sent in, a new string _id will be
+// generated and returned; if a fallbackId is provided, it will be returned
+// instead.
+Mongo.Collection._rewriteSelector = (selector, fallbackId) => {
```
Comment (benjamn) [inline packages/mongo/collection.js]: Lets make `fallbackId` an option, e.g.
```js
Mongo.Collection._rewriteSelector = (selector, {
  fallbackId = Random.id()
} = {}) => {
```

**Comment by hwillson** [comment]
I’ve made these changes with a slight tweak - since the `fallbackId` is only needed if a falsey `_id` is passed in, we’d take a small performance hit if we set a default `fallbackId` using `Random.id()` on each call of `_rewriteSelector` (when using a `fallbackId` isn’t always needed). I’ve left the `Random.id()` call out of the function signature. Thanks for the review @benjamn!

**Comment by crapthings** [comment]
METEOR@1.6.1-beta.21

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

feit:server-picker

meteor-base@1.2.0             # Packages every Meteor app needs to have
mongo@1.3.1                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.5   # CSS minifier run for production mode
standard-minifier-js@2.2.0    # JS minifier run for production mode
ecmascript@0.9.0              # Enable ECMAScript2015+ syntax in app code

meteorhacks:kadira

accounts-password@1.5.0
kadira:flow-router
dburles:collection-helpers
aldeed:simple-schema@1.5.4
aldeed:collection2
matb33:collection-hooks
vsivsi:file-collection
reywood:publish-composite
check@1.2.5
tmeasday:publish-counts
maximum:server-transform
#meteorhacks:fast-render
stylus@2.513.13
http@1.3.0
accounts-base@1.4.0
lvfang:aggregate
random@1.0.10
meteorhacks:zones
meteorhacks:unblock
peerlibrary:control-mergebox
ccorcos:subs-cache

crapthings:cao
lvfang:intl
shell-server
dynamic-import
```

```
=> Exited with code: 1
W20171222-15:35:25.129(8)? (STDERR) /Users/monsterstep/.meteor/packages/meteor-tool/.1.6.1-beta.21.qhrpdx.u2i9j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171222-15:35:25.130(8)? (STDERR) 						throw(ex);
W20171222-15:35:25.130(8)? (STDERR) 						^
W20171222-15:35:25.130(8)? (STDERR)
W20171222-15:35:25.131(8)? (STDERR) TypeError: Mongo.Collection._rewriteSelector is not a function
W20171222-15:35:25.131(8)? (STDERR)     at new CursorDescription (packages/mongo/mongo_driver.js:846:36)
W20171222-15:35:25.131(8)? (STDERR)     at MongoConnection.find (packages/mongo/mongo_driver.js:772:11)
W20171222-15:35:25.131(8)? (STDERR)     at packages/peerlibrary_reactive-mongo.js:35:91
W20171222-15:35:25.131(8)? (STDERR)     at packages/peerlibrary_reactive-mongo.js:135:4
W20171222-15:35:25.131(8)? (STDERR)     at packages/peerlibrary_reactive-mongo.js:139:4
W20171222-15:35:25.132(8)? (STDERR)     at packages/peerlibrary_reactive-mongo.js:145:3
W20171222-15:35:25.132(8)? (STDERR)     at infos.forEach.info (/Users/monsterstep/dev/cube-patch/cube/.meteor/local/build/programs/server/boot.js:415:13)
W20171222-15:35:25.132(8)? (STDERR)     at Array.forEach (<anonymous>)
W20171222-15:35:25.132(8)? (STDERR)     at /Users/monsterstep/dev/cube-patch/cube/.meteor/local/build/programs/server/boot.js:414:9
W20171222-15:35:25.132(8)? (STDERR)     at /Users/monsterstep/dev/cube-patch/cube/.meteor/local/build/programs/server/boot.js:468:5
W20171222-15:35:25.132(8)? (STDERR)     at Function.run (/Users/monsterstep/dev/cube-patch/cube/.meteor/local/build/programs/server/profile.js:510:12)
W20171222-15:35:25.133(8)? (STDERR)     at /Users/monsterstep/dev/cube-patch/cube/.meteor/local/build/programs/server/boot.js:467:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

image

i don't have peerlibrary_reactive-mongo inside packages/
