### PR TITLE
 fix: Lazy-load vscode-nsfw to support RHEL 8

### LINKED ISSUE #13649: Latest meteor is incompatible with RHEL8
Installed the latest meteor version (currently 3.1.2) and just running meteor fails with an error about package `vscode-nsfw` not being able to load `nsfw.node` because it depends on `GLIBCXX_3.4.26`, but the latest RHEL8 version of`libstdc++` is only at `GLIBCXX_3.4.25`, one micro version before the one needed.

I'm surprised that plain meteor, e.g., run as "meteor --version" would depend on an esoteric C++ node extension somehow related to the vscode editor?

### PR DESCRIPTION
**Pull request by sanki92**
## Problem
Meteor crashes on RHEL 8 / Rocky Linux 8 / AlmaLinux 8:

```
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found
(required by .../vscode-nsfw/build/Release/nsfw.node)
```

RHEL 8 has GLIBCXX_3.4.25, but vscode-nsfw needs 3.4.26. The `import nsfw from 'vscode-nsfw'` in `safe-watcher-legacy.ts` loads immediately at startup, even when using modern mode with `@parcel/watcher`.

## Solution
Lazy-load vscode-nsfw only when `watcherLibrary === 'nsfw'`:

```typescript
let nsfw: any = null;
function getNsfw() {
    if (nsfw === null) {
        try {
            nsfw = require('vscode-nsfw');
        } catch (error: any) {
            console.error('Failed to load vscode-nsfw:', error.message);
            nsfw = false;
            watcherEnabled = false;
        }
    }
    return nsfw;
}
```

## Changes
- Removed top-level vscode-nsfw import
- Added `getNsfw()` lazy-loading function
- Updated `fireNames` and `addWatchRoot()` to use `getNsfw()`
- Falls back to polling if native module fails

### Tested on Rocky Linux 8:

**Before fix:**
```bash
$ meteor --version
node:internal/modules/cjs/loader:1846
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/.meteor/packages/meteor-tool/.3.3.1.mmbrzi3t9w++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/vscode-nsfw/build/Release/nsfw.node)
    at Object..node (node:internal/modules/cjs/loader:1846:18)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1423:32)
    at Module.Mp.load (/tools/static-assets/server/runtime.js:35:31)
    at Function._load (node:internal/modules/cjs/loader:1246:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1445:12)
    at Module.mod.require (/root/.meteor/packages/meteor-tool/.3.3.1.mmbrzi3t9w++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/root/.meteor/packages/meteor-tool/.3.3.1.mmbrzi3t9w++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/vscode-nsfw/js/src/index.js:4:14) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v22.18.0
```

**After fix:**
```bash
$ meteor --version --allow-superuser
Meteor 3.3.2

$ meteor --help
Usage: meteor [--release <release>] [--help] <built-in command> [args]
       meteor help <built-in command>
       meteor [--version] [--arch]
...

$ meteor create test-app --bare
Created a new Meteor app in 'test-app'.

To run your new app:
  cd test-app
  meteor
```

Fixes #13649

### CODE REVIEW

**Comment by nachocodoner** [comment]
Looks good. I will follow your steps to reproduce it and validate the fix. Setting it for Meteor 3.4.1.

https://github.com/meteor/meteor/issues/13649#issuecomment-3661078875

Thank you so much for your work and detailed PRs! 🚀

File: tools/fs/safe-watcher-legacy.ts [hunk 1]
```diff
@@ -444,12 +469,11 @@ export function addWatchRoot(absPath: string) {
 
     // TODO: check if there are any existing watchers that are children of this
     // watcher and stop them
-
-    nsfw(
+nsfwLib(
```
Comment (italojs) [inline tools/fs/safe-watcher-legacy.ts]: Could you fix the indentation, it should match the last `for`

**Review by italojs — CHANGES_REQUESTED** [review]

File: tools/fs/safe-watcher-legacy.ts (hunk 1 above)
Comment (sanki92) [reply tools/fs/safe-watcher-legacy.ts]: Fixed

**Review by italojs — DISMISSED** [review]

**Comment by nachocodoner** [comment]
I’ve seen a failure in the Windows check, but I believe it’s related to flaky behavior that I’m currently investigating. This PR should be fine to merge. I’ll merge it into 3.4.1 shortly.

**Review by nachocodoner — APPROVED** [review]
