### PR TITLE
Fix subscription still resetting documents

### LINKED ISSUE #13212: [Meteor 3] critic regression: recalling Meteor.subscribe() with different params remove all documents and reinsert all documents
On the client:
```
Tracker.autorun(() => {
  const caseIds = _.pluck(Cases.find().fetch(), '_id');
  Meteor.subscribe('messages', caseIds);
});
```
On the server:
```
Meteor.publish('messages', function (caseIds) {
  return Messages.find({ caseId: { $in: caseIds } });
});
```

When Cases changes :

In 2.16, it only adds the new doc:

image

In 3.0-rc4, it removes all doc and inserts them again:

image

### PR DESCRIPTION
**Pull request by leonardoventurini**
An image speaks more than a thousand words:

image

### CODE REVIEW

**Review by denihs — APPROVED** [review]

File: packages/ddp-server/livedata_server.js [hunk 1]
```diff
@@ -1265,13 +1263,15 @@ Object.assign(Subscription.prototype, {
...
 
-      this._publishCursorPromise = Promise.all(
-        res.map(c => c._publishCursor(self))
-      )
-        .then(() => {
-          self.ready();
-        })
-        .catch((e) => self.error(e));
+      try {
+        for (const cur of res) {
```
Comment (afrokick) [inline packages/ddp-server/livedata_server.js]: why we need to change from parallel handling into sequenced?
`await Promise.all(res.map(cur => cur._publishCursor(self))` seems good.

Comment (leonardoventurini) [reply packages/ddp-server/livedata_server.js]: Subscription parameter change needs be handled sync/waited for in the server, otherwise the client presents the behavior reported, being completely removed and then re-added. Not entirely sure how all this works, perhaps some can be handled in parallel but not others.

Comment (leonardoventurini) [reply packages/ddp-server/livedata_server.js]: I will try your approach, I think it might still make sense.

Comment (leonardoventurini) [reply packages/ddp-server/livedata_server.js]: Looks like it still works, thanks @afrokick !!

**Comment by leonardoventurini** [comment]
I added a test for it, here is a breakdown

image

File: packages/ddp-client/test/livedata_connection_tests.js
Comment (StorytellerCZ) [inline packages/ddp-client/test/livedata_connection_tests.js:1]: Can you explain why it is no longer needed?

Comment (leonardoventurini) [reply packages/ddp-client/test/livedata_connection_tests.js:1]: It wasn't the problem in the first place, so for simplicity and risk management I thought best to remove it and the change made before (https://github.com/meteor/meteor/pull/13236/commits/f169bc81bbde74cc6ebf0fe95b2fcf035f6ba5ee). But if you, @zodern or @radekmie think I should keep it I can (already confirmed with @denihs).

Comment (leonardoventurini) [reply packages/ddp-client/test/livedata_connection_tests.js:1]: Actually I noticed some flakyness after more testing, adding it back solves it, so it is truly part of the fix
